CREATE SEQUENCE SEQ_ID;
CREATE SEQUENCE SEQ_WORKSCOPE_ID;

CREATE TABLE WORKSCOPE
(
  ID BIGINT DEFAULT nextval('SEQ_WORKSCOPE_ID') NOT NULL,
  VERSION BIGINT NOT NULL,
  ESN VARCHAR(255) NOT NULL,
  TITLE VARCHAR(4000) NOT NULL,
  ENGINE_DETAILS JSON,
  HEALTH_INSTRUCTIONS JSON,
  LINKS JSON,
  STATUS VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP
 );

ALTER TABLE WORKSCOPE ADD PRIMARY KEY (ID, VERSION);
