CREATE SEQUENCE SEQ_INSPECTION_INSTRUCTIONS_ID;

CREATE TABLE ENGINE_INSPECTION_INSTRUCTIONS_TEMPLATE
(
  ID BIGINT DEFAULT nextval('SEQ_INSPECTION_INSTRUCTIONS_ID') PRIMARY KEY NOT NULL,
  ENGINE_FAMILY VARCHAR(255) NOT NULL,
  ENGINE_SERIES VARCHAR(255),
  ENGINE_MODEL VARCHAR(255),
  INSPECTION_INSTRUCTIONS JSON,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP DEFAULT NOW(),
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
 );
